// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: API_Link

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
	"github.com/hashicorp/terraform-plugin-log/tflog"
    "context"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ context.Context = context.Background()



type ApiLinkResourceModel struct {
	ResourceModelBase `tfsdk:"-"`
    Href types.String `tfsdk:"href" json:"href,optional,omitempty" fpro:"href"`
        Rel types.String `tfsdk:"rel" json:"rel,optional,omitempty" fpro:"rel"`
        Type types.String `tfsdk:"type" json:"type,optional,omitempty" fpro:"type"`
        
}

func UselessApiLinkResourceModel() {
	tflog.Debug(context.Background(), "This function is here to avoid import errors")
	
}