// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Third_Party_Monitoring

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
	"github.com/hashicorp/terraform-plugin-log/tflog"
    "context"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ context.Context = context.Background()



type ThirdPartyMonitoringResourceModel struct {
	ResourceModelBase `tfsdk:"-"`
    Encoding types.String `tfsdk:"encoding" json:"encoding,optional,omitempty" `
        LoggingProfileRef types.String `tfsdk:"logging_profile_ref" json:"logging_profile_ref,optional,omitempty" `
        MonitoringLogServerRef types.String `tfsdk:"monitoring_log_server_ref" json:"monitoring_log_server_ref,optional,omitempty" `
        Netflow types.Bool `tfsdk:"netflow" json:"netflow,optional,omitempty" `
        ProbingProfileRef types.String `tfsdk:"probing_profile_ref" json:"probing_profile_ref,optional,omitempty" `
        SnmpTrap types.Bool `tfsdk:"snmp_trap" json:"snmp_trap,optional,omitempty" `
        TimeZone types.String `tfsdk:"time_zone" json:"time_zone,optional,omitempty" `
        
}

func UselessThirdPartyMonitoringResourceModel() {
	tflog.Debug(context.Background(), "This function is here to avoid import errors")
	
}