// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Host

package provider

import (
    "github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
	"github.com/hashicorp/terraform-plugin-log/tflog"
    "context"
)

// to avoid import errors if unused
var _ = customfield.NewNestedObjectType[struct{}](nil)
var _ = types.String{}
var _ context.Context = context.Background()



type HostResourceModel struct {
	ResourceModelBase `tfsdk:"-"`
	ID                    types.String `tfsdk:"id"`
    Address types.String `tfsdk:"address" json:"address,optional,omitempty" `
        AdminDomain types.String `tfsdk:"admin_domain" json:"admin_domain,optional,omitempty" fpro:"admin_domain"`
        Comment types.String `tfsdk:"comment" json:"comment,optional,omitempty" `
        Etag types.String `tfsdk:"etag" json:"etag,optional,omitempty" fpro:"etag"`
        Ipv6Address types.String `tfsdk:"ipv6_address" json:"ipv6_address,optional,omitempty" `
        Key types.Int64 `tfsdk:"key" json:"key,optional,omitempty" fpro:"key"`
        Link customfield.NestedObjectList[ApiLinkResourceModel] `tfsdk:"link" json:"link,optional,omitempty" fpro:"link"`
        Lk customfield.Map[types.String] `tfsdk:"lk" json:"-" `
        LocationRef types.String `tfsdk:"location_ref" json:"location_ref,optional,omitempty" `
        Locked types.Bool `tfsdk:"locked" json:"locked,optional,omitempty" fpro:"locked"`
        Name types.String `tfsdk:"name" json:"name,optional,omitempty" `
        ReadOnly types.Bool `tfsdk:"read_only" json:"read_only,optional,omitempty" fpro:"read_only"`
        Secondary *[]types.String `tfsdk:"secondary" json:"secondary,optional,omitempty" `
        System types.Bool `tfsdk:"system" json:"system,optional,omitempty" fpro:"system"`
        SystemKey types.Int64 `tfsdk:"system_key" json:"system_key,optional,omitempty" fpro:"system_key"`
        ThirdPartyMonitoring *ThirdPartyMonitoringResourceModel `tfsdk:"third_party_monitoring" json:"third_party_monitoring,optional,omitempty" `
        ToolsProfileRef types.String `tfsdk:"tools_profile_ref" json:"tools_profile_ref,optional,omitempty" `
        Trashed types.Bool `tfsdk:"trashed" json:"trashed,optional,omitempty" fpro:"trashed"`
        
}

func UselessHostResourceModel() {
	tflog.Debug(context.Background(), "This function is here to avoid import errors")
	
}