// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from resource and datasource lists.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// Resources returns the list of resources supported by this provider.
func (p *SmcProvider) Resources(_ context.Context) []func() resource.Resource {
    return []func() resource.Resource{
        NewHostResource,
  }
}

// DataSources returns the list of data sources supported by this provider.
func (p *SmcProvider) DataSources(_ context.Context) []func() datasource.DataSource {
    return []func() datasource.DataSource{
        NewElementDataSource,
  }
}
