// Code generated by tfsmcgen. DO NOT EDIT.
// This file was automatically generated from OpenAPI schema: Single_Firewall
// Package provider implements the SMC Terraform provider resources and data sources.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"

	"github.com/terraform-providers/terraform-provider-smc/internal/customfield"
)

// to avoid import errors if unused
var _ = types.String{}
var _ =  (*planmodifier.Bool)(nil)
var _ = (*customfield.NestedObjectType[struct{}])(nil)
var _ = stringplanmodifier.UseStateForUnknown()
var _ = boolplanmodifier.UseStateForUnknown()
var _ = int64planmodifier.UseStateForUnknown()
var _ = listplanmodifier.UseStateForUnknown()
var _ = listdefault.StaticValue




func GetThirdPartyMonitoringSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
    return map[string]schema.Attribute {
       "encoding": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The character encoding used for log reception, which determines how text is interpreted.",
        },
       "logging_profile_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a Logging Profile used for Third Party Monitoring, defining how the Log Server converts Syslog data received from a particular type of third-party component into Stonesoft Management Center log entries.",
        },
       "monitoring_log_server_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a Log Server, which is a component of the Management Center responsible for storing and managing log (and alert) data, and analyzing and correlating events detected by multiple NGFW Engines.",
        },
       "netflow": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether NetFlow data reception is enabled for this device.",
       },
       "probing_profile_ref": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "This represents a Probing Profile used in Third Party Monitoring. It contains settings that define how a Log Server monitors third-party components.",
        },
       "snmp_trap": schema.BoolAttribute {
         Optional: true, // todo optional parameters
         Description: "Indicates whether SNMP trap reception is enabled for this device.",
       },
       "time_zone": schema.StringAttribute {
       Optional: true, // todo optional parameters
       Description: "The time zone ID for log reception, which determines the time zone used for timestamps in logs.",
        },

    }
}

func GetThirdPartyMonitoringSchemaBlocks(ctx context.Context) map[string]schema.Block {

    return map[string]schema.Block{
 
    }
}